{
 "title": "DORA",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights",
  "DORA"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT name AS __text, name AS __value FROM repos ORDER BY name"
   },
   {
    "name": "dora_report",
    "label": "DORA Report",
    "query": "select dora_report from dora_benchmarks"
   },
   {
    "name": "title_value",
    "label": "TitleValue",
    "query": "SELECT \n  CASE \n    WHEN dora_report = '2023' THEN \"Failed Deployment Recovery Time\"\n    WHEN dora_report = '2021' THEN \"Median Time to Restore Service\"\n    ELSE NULL \n  END AS title_value\nFROM dora_benchmarks\nWHERE dora_report = '${dora_report:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- See [how to config](https://devlake.apache.org/docs/DORA) this dashboard\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, webhook, etc. \n  - `Pull Requests` from GitHub PRs, GitLab MRs, BitBucket PRs, Azure DevOps PRs, etc.\n  - `Incidents` from Jira issues, GitHub issues, TAPD issues, PagerDuty Incidents, etc. \n- Transformation Required: Define `deployments` and `incidents` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project.\n- You can validate/debug this dashboard with the [DORA validation dashboard](/grafana/d/KGkUnV-Vz/dora-dashboard-validation)\n- DORA benchmarks vary in different years. You can switch the benchmarks to change them.\n- In DORA's official report in 2023, metric 'failed deployment recovery time' has replaced 'MTTR'."
   }
  },
  {
   "title": "Overall DORA Metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "-- Metric 1: Deployment Frequency\nwith last_few_calendar_months as(\n  -- construct the last few calendar months within the selected time period in the top-right corner\n  SELECT\n    CAST(($__timeTo() - INTERVAL (H + T + U) DAY) AS date) day\n  FROM\n    (\n      SELECT\n        0 H\n      UNION\n      ALL\n      SELECT\n        100\n      UNION\n      ALL\n      SELECT\n        200\n      UNION\n      ALL\n      SELECT\n        300\n    ) H\n    CROSS JOIN (\n      SELECT\n        0 T\n      UNION\n      ALL\n      SELECT\n        10\n      UNION\n      ALL\n      SELECT\n        20\n      UNION\n      ALL\n      SELECT\n        30\n      UNION\n      ALL\n      SELECT\n        40\n      UNION\n      ALL\n      SELECT\n        50\n      UNION\n      ALL\n      SELECT\n        60\n      UNION\n      ALL\n      SELECT\n        70\n      UNION\n      ALL\n      SELECT\n        80\n      UNION\n      ALL\n      SELECT\n        90\n    ) T\n    CROSS JOIN (\n      SELECT\n        0 U\n      UNION\n      ALL\n      SELECT\n        1\n      UNION\n      ALL\n      SELECT\n        2\n      UNION\n      ALL\n      SELECT\n        3\n      UNION\n      ALL\n      SELECT\n        4\n      UNION\n      ALL\n      SELECT\n        5\n      UNION\n      ALL\n      SELECT\n        6\n      UNION\n      ALL\n      SELECT\n        7\n      UNION\n      ALL\n      SELECT\n        8\n      UNION\n      ALL\n      SELECT\n        9\n    ) U\n  WHERE\n    ($__timeTo() - INTERVAL (H + T + U) DAY) > $__timeFrom()\n),\n_production_deployment_days as(\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(DATE(cdc.finished_date)) as day\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    AND pm.`table` = 'cicd_scopes'\n    JOIN repos r ON r.id = pm.row_id\n  WHERE\n    (\n      '${project:raw}' = '$__all'\n      OR r.name IN (${project:singlequote})\n    )\n    AND cdc.result = 'SUCCESS'\n    AND cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n),\n_days_weekly_deploy as(\n  -- calculate the number of deployment days every week\n  SELECT\n    date(\n      DATE_ADD(\n        last_few_calendar_months.day,\n        INTERVAL - WEEKDAY(last_few_calendar_months.day) DAY\n      )\n    ) as week,\n    MAX(\n      if(\n        _production_deployment_days.day is not null,\n        1,\n        0\n      )\n    ) as weeks_deployed,\n    COUNT(distinct _production_deployment_days.day) as days_deployed\n  FROM\n    last_few_calendar_months\n    LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day\n  GROUP BY\n    week\n),\n_days_monthly_deploy as(\n  -- calculate the number of deployment days every month\n  SELECT\n    date(\n      DATE_ADD(\n        last_few_calendar_months.day,\n        INTERVAL - DAY(last_few_calendar_months.day) + 1 DAY\n      )\n    ) as month,\n    MAX(\n      if(\n        _production_deployment_days.day is not null,\n        1,\n        null\n      )\n    ) as months_deployed,\n    COUNT(distinct _production_deployment_days.day) as days_deployed\n  FROM\n    last_few_calendar_months\n    LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day\n  GROUP BY\n    month\n),\n_days_six_months_deploy AS (\n  SELECT\n    month,\n    SUM(days_deployed) OVER (\n      ORDER BY\n        month ROWS BETWEEN 5 PRECEDING\n        AND CURRENT ROW\n    ) AS days_deployed_per_six_months,\n    COUNT(months_deployed) OVER (\n      ORDER BY\n        month ROWS BETWEEN 5 PRECEDING\n        AND CURRENT ROW\n    ) AS months_deployed_count,\n    ROW_NUMBER() OVER (\n      PARTITION BY DATE_FORMAT(month, '%Y-%m') DIV 6\n      ORDER BY\n        month DESC\n    ) AS rn\n  FROM\n    _days_monthly_deploy\n),\n_median_number_of_deployment_days_per_week_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        days_deployed\n    ) as ranks\n  FROM\n    _days_weekly_deploy\n),\n_median_number_of_deployment_days_per_week as(\n  SELECT\n    max(days_deployed) as median_number_of_deployment_days_per_week\n  FROM\n    _median_number_of_deployment_days_per_week_ranks\n  WHERE\n    ranks <= 0.5\n),\n_median_number_of_deployment_days_per_month_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        days_deployed\n    ) as ranks\n  FROM\n    _days_monthly_deploy\n),\n_median_number_of_deployment_days_per_month as(\n  SELECT\n    max(days_deployed) as median_number_of_deployment_days_per_month\n  FROM\n    _median_number_of_deployment_days_per_month_ranks\n  WHERE\n    ranks <= 0.5\n),\n_days_per_six_months_deploy_by_filter AS (\n  SELECT\n    month,\n    days_deployed_per_six_months,\n    months_deployed_count\n  FROM\n    _days_six_months_deploy\n  WHERE\n    rn % 6 = 1\n),\n_median_number_of_deployment_days_per_six_months_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        days_deployed_per_six_months\n    ) as ranks\n  FROM\n    _days_per_six_months_deploy_by_filter\n),\n_median_number_of_deployment_days_per_six_months as(\n  SELECT\n    min(days_deployed_per_six_months) as median_number_of_deployment_days_per_six_months,\n    min(months_deployed_count) as is_collected\n  FROM\n    _median_number_of_deployment_days_per_six_months_ranks\n  WHERE\n    ranks >= 0.5\n),\n_metric_deployment_frequency as (\n  SELECT\n    'Deployment frequency' as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)'\n        WHEN median_number_of_deployment_days_per_week >= 1 THEN 'Between once per day and once per week(high)'\n        WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per week and once per month(medium)'\n        WHEN median_number_of_deployment_days_per_month < 1\n        AND is_collected IS NOT NULL THEN 'Fewer than once per month(low)'\n        ELSE \"N/A. Please check if you have collected deployments.\"\n      END\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)'\n        WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per day and once per month(high)'\n        WHEN median_number_of_deployment_days_per_six_months >= 1 THEN 'Between once per month and once every 6 months(medium)'\n        WHEN median_number_of_deployment_days_per_six_months < 1\n        AND is_collected IS NOT NULL THEN 'Fewer than once per six months(low)'\n        ELSE \"N/A. Please check if you have collected deployments.\"\n      END\n      ELSE 'Invalid dora report'\n    END AS value\n  FROM\n    _median_number_of_deployment_days_per_week,\n    _median_number_of_deployment_days_per_month,\n    _median_number_of_deployment_days_per_six_months\n),\n-- Metric 2: median lead time for changes\n_pr_stats as (\n  -- get the cycle time of PRs deployed by the deployments finished in the selected period\n  SELECT\n    distinct pr.id,\n    ppm.pr_cycle_time\n  FROM\n    pull_requests pr\n    join project_pr_metrics ppm on ppm.id = pr.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id\n    AND pm.`table` = 'repos'\n    JOIN repos r ON r.id = pm.row_id\n    join cicd_deployment_commits cdc on ppm.deployment_commit_id = cdc.id\n  WHERE\n    (\n      '${project:raw}' = '$__all'\n      OR r.name IN (${project:singlequote})\n    )\n    and pr.merged_date is not null\n    and ppm.pr_cycle_time is not null\n    and $__timeFilter(cdc.finished_date)\n),\n_median_change_lead_time_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        pr_cycle_time\n    ) as ranks\n  FROM\n    _pr_stats\n),\n_median_change_lead_time as(\n  -- use median PR cycle time as the median change lead time\n  SELECT\n    max(pr_cycle_time) as median_change_lead_time\n  FROM\n    _median_change_lead_time_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_change_lead_time as (\n  SELECT\n    'Lead time for changes' as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN median_change_lead_time < 24 * 60 THEN \"Less than one day(elite)\"\n        WHEN median_change_lead_time < 7 * 24 * 60 THEN \"Between one day and one week(high)\"\n        WHEN median_change_lead_time < 30 * 24 * 60 THEN \"Between one week and one month(medium)\"\n        WHEN median_change_lead_time >= 30 * 24 * 60 THEN \"More than one month(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/pull_requests.\"\n      END\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_change_lead_time < 60 THEN \"Less than one hour(elite)\"\n        WHEN median_change_lead_time < 7 * 24 * 60 THEN \"Less than one week(high)\"\n        WHEN median_change_lead_time < 180 * 24 * 60 THEN \"Between one week and six months(medium)\"\n        WHEN median_change_lead_time >= 180 * 24 * 60 THEN \"More than six months(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/pull_requests.\"\n      END\n      ELSE 'Invalid dora report'\n    END AS value\n  FROM\n    _median_change_lead_time\n),\n-- Metric 3: change failure rate\n_deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    AND pm.`table` = 'cicd_scopes'\n    JOIN repos r ON r.id = pm.row_id\n  WHERE\n    (\n      '${project:raw}' = '$__all'\n      OR r.name IN (${project:singlequote})\n    )\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(\n      distinct case\n        when i.id is not null then d.deployment_id\n        else null\n      end\n    ) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n),\n_change_failure_rate as (\n  SELECT\n    case\n      when count(deployment_id) is null then null\n      else sum(has_incident) / count(deployment_id)\n    end as change_failure_rate\n  FROM\n    _failure_caused_by_deployments\n),\n_is_collected_data as(\n  SELECT\n    CASE\n      WHEN COUNT(i.id) = 0\n      AND COUNT(cdc.id) = 0 THEN 'No All'\n      WHEN COUNT(i.id) = 0 THEN 'No Incidents'\n      WHEN COUNT(cdc.id) = 0 THEN 'No Deployments'\n    END AS is_collected\n  FROM\n    (\n      SELECT\n        1\n    ) AS dummy\n    LEFT JOIN incidents i ON 1 = 1\n    LEFT JOIN cicd_deployment_commits cdc ON 1 = 1\n),\n_metric_cfr as (\n  SELECT\n    'Change failure rate' as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n        WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n        WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n        WHEN change_failure_rate <=.05 THEN \"0-5%(elite)\"\n        WHEN change_failure_rate <=.10 THEN \"5%-10%(high)\"\n        WHEN change_failure_rate <=.15 THEN \"10%-15%(medium)\"\n        WHEN change_failure_rate >.15 THEN \"> 15%(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n      END\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n        WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n        WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n        WHEN change_failure_rate <=.15 THEN \"0-15%(elite)\"\n        WHEN change_failure_rate <=.20 THEN \"16%-20%(high)\"\n        WHEN change_failure_rate <=.30 THEN \"21%-30%(medium)\"\n        WHEN change_failure_rate >.30 THEN \"> 30%(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n      END\n      ELSE 'Invalid dora report'\n    END AS value\n  FROM\n    _change_failure_rate,\n    _is_collected_data\n),\n--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\n_incidents_for_deployments as (\n  SELECT\n    i.id as incident_id,\n    i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    fd.deployment_id as caused_by_deployment,\n    fd.deployment_finished_date,\n    date_format(fd.deployment_finished_date, '%y/%m') as deployment_finished_month\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n),\n_recovery_time_ranks as (\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        TIMESTAMPDIFF(\n          MINUTE,\n          deployment_finished_date,\n          incident_resolution_date\n        )\n    ) as ranks\n  FROM\n    _incidents_for_deployments\n),\n_median_recovery_time as (\n  SELECT\n    max(\n      TIMESTAMPDIFF(\n        MINUTE,\n        deployment_finished_date,\n        incident_resolution_date\n      )\n    ) as median_recovery_time\n  FROM\n    _recovery_time_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_recovery_time_2023_report as(\n  SELECT\n    \"Failed deployment recovery time\" as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN median_recovery_time < 60 THEN \"Less than one hour(elite)\"\n        WHEN median_recovery_time < 24 * 60 THEN \"Less than one day(high)\"\n        WHEN median_recovery_time < 7 * 24 * 60 THEN \"Between one day and one week(medium)\"\n        WHEN median_recovery_time >= 7 * 24 * 60 THEN \"More than one week(low)\"\n        ELSE \"N/A. Please check if you have collected deployments or incidents.\"\n      END\n    END AS median_recovery_time\n  FROM\n    _median_recovery_time\n),\n--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \n_incidents as (\n  -- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i\n    join project_mapping pm on i.scope_id = pm.row_id\n    AND pm.`table` = i.`table`\n    JOIN repos r ON r.id = pm.row_id\n  WHERE\n    (\n      '${project:raw}' = '$__all'\n      OR r.name IN (${project:singlequote})\n    )\n    and $__timeFilter(i.resolution_date)\n),\n_median_mttr_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        lead_time_minutes\n    ) as ranks\n  FROM\n    _incidents\n),\n_median_mttr as(\n  SELECT\n    max(lead_time_minutes) as median_time_to_resolve\n  FROM\n    _median_mttr_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_mttr_2021_report as(\n  SELECT\n    \"Time to restore service\" as metric,\n    CASE\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_time_to_resolve < 60 THEN \"Less than one hour(elite)\"\n        WHEN median_time_to_resolve < 24 * 60 THEN \"Less than one day(high)\"\n        WHEN median_time_to_resolve < 7 * 24 * 60 THEN \"Between one day and one week(medium)\"\n        WHEN median_time_to_resolve >= 7 * 24 * 60 THEN \"More than one week(low)\"\n        ELSE \"N/A. Please check if you have collected incidents.\"\n      END\n    END AS median_time_to_resolve\n  FROM\n    _median_mttr\n),\n_metric_mrt_or_mm as(\n  SELECT\n    metric,\n    median_recovery_time AS value\n  FROM\n    _metric_recovery_time_2023_report\n  WHERE\n    ('$dora_report') = '2023'\n  UNION\n  SELECT\n    metric,\n    median_time_to_resolve AS value\n  FROM\n    _metric_mttr_2021_report\n  WHERE\n    ('$dora_report') = '2021'\n),\n_final_results as (\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m1.metric as _metric,\n    m1.value\n  FROM\n    dora_benchmarks db\n    left join _metric_deployment_frequency m1 on db.metric = m1.metric\n  WHERE\n    m1.metric is not null\n    and db.dora_report = ('$dora_report')\n  union\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m2.metric as _metric,\n    m2.value\n  FROM\n    dora_benchmarks db\n    left join _metric_change_lead_time m2 on db.metric = m2.metric\n  WHERE\n    m2.metric is not null\n    and db.dora_report = ('$dora_report')\n  union\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m3.metric as _metric,\n    m3.value\n  FROM\n    dora_benchmarks db\n    left join _metric_cfr m3 on db.metric = m3.metric\n  WHERE\n    m3.metric is not null\n    and db.dora_report = ('$dora_report')\n  union\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m4.metric as _metric,\n    m4.value\n  FROM\n    dora_benchmarks db\n    left join _metric_mrt_or_mm m4 on db.metric = m4.metric\n  WHERE\n    m4.metric is not null\n    and db.dora_report = ('$dora_report')\n)\nSELECT\n  metric,\n  replace(metric, ' ', '-') as metric_hidden,\n  case\n    when low = value then low\n    else null\n  end as low,\n  case\n    when medium = value then medium\n    else null\n  end as medium,\n  case\n    when high = value then high\n    else null\n  end as high,\n  case\n    when elite = value then elite\n    else null\n  end as elite\nFROM\n  _final_results\nORDER BY\n  id\n"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "description": "How often an organization deploys code to production or release it to end users\n\n# 2023 Benchmarks\n- **Elite**: >= 7 deployment days per week\n- **High**: >= 1 deployment day per week\n- **Medium**: >= 1 deployment day per month\n- **Low**: < 1 deployment day per month\n# 2021 Benchmarks\n- **Elite**: >= 7 deployment days per week\n- **High**: >= 1 deployment day per month\n- **Medium**: >= 1  deployment day per six months\n- **Low**: < 1 deployment day per six months",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 1: Deployment Frequency\nWITH last_few_calendar_months AS (\n    SELECT CAST(($__timeTo() - INTERVAL (H+T+U) DAY) AS DATE) AS day\n    FROM (SELECT 0 H UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) H\n    CROSS JOIN (SELECT 0 T UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30\n                UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60\n                UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) T\n    CROSS JOIN (SELECT 0 U UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3\n                UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6\n                UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) U\n    WHERE ($__timeTo() - INTERVAL (H+T+U) DAY) > $__timeFrom()\n),\n\n_production_deployment_days AS (\n    SELECT\n        cdc.cicd_deployment_id AS deployment_id,\n        MAX(DATE(cdc.finished_date)) AS day\n    FROM cicd_deployment_commits cdc\n    JOIN repos r ON r.id = cdc.repo_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND cdc.result = 'SUCCESS'\n        AND cdc.environment = 'PRODUCTION'\n    GROUP BY 1\n),\n\n_days_weekly_deploy AS (\n    SELECT\n        DATE(DATE_ADD(l.day, INTERVAL -WEEKDAY(l.day) DAY)) AS week,\n        MAX(IF(p.day IS NOT NULL, 1, NULL)) AS weeks_deployed,\n        COUNT(DISTINCT p.day) AS days_deployed\n    FROM last_few_calendar_months l\n    LEFT JOIN _production_deployment_days p ON p.day = l.day\n    GROUP BY week\n),\n\n_days_monthly_deploy AS (\n    SELECT\n        DATE(DATE_ADD(l.day, INTERVAL -DAY(l.day)+1 DAY)) AS month,\n        MAX(IF(p.day IS NOT NULL, 1, NULL)) AS months_deployed,\n        COUNT(DISTINCT p.day) AS days_deployed\n    FROM last_few_calendar_months l\n    LEFT JOIN _production_deployment_days p ON p.day = l.day\n    GROUP BY month\n),\n\n_days_six_months_deploy AS (\n  SELECT\n    month,\n    SUM(days_deployed) OVER (ORDER BY month ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS days_deployed_per_six_months,\n    COUNT(months_deployed) OVER (ORDER BY month ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS months_deployed_count,\n    ROW_NUMBER() OVER (PARTITION BY DATE_FORMAT(month,'%Y-%m') DIV 6 ORDER BY month DESC) AS rn\n  FROM _days_monthly_deploy\n),\n\n_median_number_of_deployment_days_per_week_ranks AS (\n    SELECT *, percent_rank() OVER (ORDER BY days_deployed) AS ranks\n    FROM _days_weekly_deploy\n),\n\n_median_number_of_deployment_days_per_week AS (\n    SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_week\n    FROM _median_number_of_deployment_days_per_week_ranks\n    WHERE ranks <= 0.5\n),\n\n_median_number_of_deployment_days_per_month_ranks AS (\n    SELECT *, percent_rank() OVER (ORDER BY days_deployed) AS ranks\n    FROM _days_monthly_deploy\n),\n\n_median_number_of_deployment_days_per_month AS (\n    SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_month\n    FROM _median_number_of_deployment_days_per_month_ranks\n    WHERE ranks <= 0.5\n),\n\n_days_per_six_months_deploy_by_filter AS (\n    SELECT month, days_deployed_per_six_months, months_deployed_count\n    FROM _days_six_months_deploy\n    WHERE rn % 6 = 1\n),\n\n_median_number_of_deployment_days_per_six_months_ranks AS (\n    SELECT *, percent_rank() OVER (ORDER BY days_deployed_per_six_months) AS ranks\n    FROM _days_per_six_months_deploy_by_filter\n),\n\n_median_number_of_deployment_days_per_six_months AS (\n    SELECT \n        MIN(days_deployed_per_six_months) AS median_number_of_deployment_days_per_six_months,\n        MIN(months_deployed_count) AS is_collected\n    FROM _median_number_of_deployment_days_per_six_months_ranks\n    WHERE ranks >= 0.5\n)\n\nSELECT \n  CASE\n    WHEN ('$dora_report') = '2023' THEN\n        CASE  \n            WHEN median_number_of_deployment_days_per_week >= 5 THEN CONCAT(median_number_of_deployment_days_per_week, ' deployment days per week(elite)')\n            WHEN median_number_of_deployment_days_per_week >= 1 THEN CONCAT(median_number_of_deployment_days_per_week, ' deployment days per week(high)')\n            WHEN median_number_of_deployment_days_per_month >= 1 THEN CONCAT(median_number_of_deployment_days_per_month, ' deployment days per month(medium)')\n            WHEN median_number_of_deployment_days_per_month < 1 AND is_collected IS NOT NULL THEN CONCAT(median_number_of_deployment_days_per_month, ' deployment days per month(low)')\n            ELSE 'N/A. Please check if you have collected deployments.'\n        END\n    WHEN ('$dora_report') = '2021' THEN\n        CASE  \n            WHEN median_number_of_deployment_days_per_week >= 5 THEN CONCAT(median_number_of_deployment_days_per_week, ' deployment days per week(elite)')\n            WHEN median_number_of_deployment_days_per_month >= 1 THEN CONCAT(median_number_of_deployment_days_per_month, ' deployment days per month(high)')\n            WHEN median_number_of_deployment_days_per_six_months >= 1 THEN CONCAT(median_number_of_deployment_days_per_six_months, ' deployment days per six months(medium)')\n            WHEN median_number_of_deployment_days_per_six_months < 1 AND is_collected IS NOT NULL THEN CONCAT(median_number_of_deployment_days_per_six_months, ' deployment days per six months(low)')\n            ELSE 'N/A. Please check if you have collected deployments.'\n        END\n    ELSE 'Invalid dora report'\n  END AS 'Deployment Frequency'\nFROM \n    _median_number_of_deployment_days_per_week,\n    _median_number_of_deployment_days_per_month,\n    _median_number_of_deployment_days_per_six_months;\n"
    }
   ]
  },
  {
   "title": "Median Lead Time for Changes In Hours",
   "type": "stat",
   "description": "The median amount of time for a code change to be deployed into production.\n\n\n# 2023 Benchmarks\n- **Elite**: Less than one day\n- **High**: Between one day and one week\n- **Medium**: Between one week and one month\n- **Low**: More than one month\n# 2021 Benchmarks\n- **Elite**: Less than one hour\n- **High**: Less than one week\n- **Medium**: Between one week and six months\n- **Low**: More than six months\n",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 2: median lead time for changes\nWITH _pr_stats AS (\n    SELECT\n        DISTINCT pr.id,\n        ppm.pr_cycle_time\n    FROM pull_requests pr\n    JOIN project_pr_metrics ppm \n        ON ppm.id = pr.id\n    JOIN cicd_deployment_commits cdc \n        ON ppm.deployment_commit_id = cdc.id\n    JOIN repos r\n        ON r.id = pr.base_repo_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND pr.merged_date IS NOT NULL\n        AND ppm.pr_cycle_time IS NOT NULL\n        AND $__timeFilter(cdc.finished_date)\n),\n\n_median_change_lead_time_ranks AS (\n    SELECT \n        *,\n        percent_rank() OVER (ORDER BY pr_cycle_time) AS ranks\n    FROM _pr_stats\n),\n\n_median_change_lead_time AS (\n    SELECT \n        MAX(pr_cycle_time) AS median_change_lead_time\n    FROM _median_change_lead_time_ranks\n    WHERE ranks <= 0.5\n)\n\nSELECT \n  CASE\n    WHEN ('$dora_report') = '2023' THEN\n        CASE\n            WHEN median_change_lead_time < 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(elite)')\n            WHEN median_change_lead_time < 7 * 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(high)')\n            WHEN median_change_lead_time < 30 * 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(medium)')\n            WHEN median_change_lead_time >= 30 * 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(low)')\n            ELSE 'N/A. Please check if you have collected deployments/pull_requests.'\n        END\n    WHEN ('$dora_report') = '2021' THEN\n        CASE\n            WHEN median_change_lead_time < 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(elite)')\n            WHEN median_change_lead_time < 7 * 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(high)')\n            WHEN median_change_lead_time < 180 * 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(medium)')\n            WHEN median_change_lead_time >= 180 * 24 * 60 THEN CONCAT(ROUND(median_change_lead_time/60,1), '(low)')\n            ELSE 'N/A. Please check if you have collected deployments/pull_requests.'\n        END\n    ELSE 'Invalid dora_report'\n  END AS median_change_lead_time\nFROM _median_change_lead_time;\n"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "description": "The percentage of changes that were made to a code that then resulted in incidents, rollbacks, or any type of production failure.\n\n# 2023 Benchmarks\n- **Elite**: (0, 5%]\n- **High**: (5%, 10%]\n- **Medium**: (10%, 15%]\n- **Low**: (15%, 100%]\n# 2021 Benchmarks\n- **Elite**: (0, 15%]\n- **High**: (16%, 20%]\n- **Medium**: (21%, 30%]\n- **Low**: (30%, 100%]\n",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate\nwith _deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(\n      distinct case\n        when i.id is not null then d.deployment_id\n        else null\n      end\n    ) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n),\n_change_failure_rate as (\n  SELECT\n    case\n      when count(deployment_id) is null then null\n      else sum(has_incident) / count(deployment_id)\n    end as change_failure_rate\n  FROM\n    _failure_caused_by_deployments\n),\n_is_collected_data as(\n  SELECT\n    CASE\n      WHEN COUNT(i.id) = 0\n      AND COUNT(cdc.id) = 0 THEN 'No All'\n      WHEN COUNT(i.id) = 0 THEN 'No Incidents'\n      WHEN COUNT(cdc.id) = 0 THEN 'No Deployments'\n    END AS is_collected\n  FROM\n    (\n      SELECT\n        1\n    ) AS dummy\n    LEFT JOIN incidents i ON 1 = 1\n    LEFT JOIN cicd_deployment_commits cdc ON 1 = 1\n)\nSELECT\n  CASE\n    WHEN ('$dora_report') = '2023' THEN CASE\n      WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n      WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n      WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n      WHEN change_failure_rate <=.05 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(elite)\")\n      WHEN change_failure_rate <=.10 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(high)\")\n      WHEN change_failure_rate <=.15 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(medium)\")\n      WHEN change_failure_rate >.15 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(low)\")\n      ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n    END\n    WHEN ('$dora_report') = '2021' THEN CASE\n      WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n      WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n      WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n      WHEN change_failure_rate <=.15 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(elite)\")\n      WHEN change_failure_rate <=.20 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(high)\")\n      WHEN change_failure_rate <=.30 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(medium)\")\n      WHEN change_failure_rate >.30 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(low)\")\n      ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n    END\n    ELSE 'No data'\n  END AS change_failure_rate\nFROM\n  _change_failure_rate,\n  _is_collected_data"
    }
   ]
  },
  {
   "title": "${title_value} In Hours",
   "type": "stat",
   "description": "# MTTR benchmarks:\ndevlake.apache.org/docs/Metrics/MTTR#how-is-it-calculated\n# FDRT benchmarks:\ndevlake.apache.org/docs/Metrics/FailedDeploymentRecoveryTime#how-is-it-calculated\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- ****** 2023 Report ******\n-- Metric 4: Failed deployment recovery time\n\nWITH _deployments AS (\n    SELECT\n        cdc.cicd_deployment_id AS deployment_id,\n        MAX(cdc.finished_date) AS deployment_finished_date\n    FROM cicd_deployment_commits cdc\n    JOIN repos r ON r.id = cdc.repo_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND cdc.result = 'SUCCESS'\n        AND cdc.environment = 'PRODUCTION'\n    GROUP BY 1\n    HAVING $__timeFilter(MAX(cdc.finished_date))\n),\n\n_incidents_for_deployments AS (\n    SELECT\n        i.id AS incident_id,\n        i.created_date AS incident_create_date,\n        i.resolution_date AS incident_resolution_date,\n        d.deployment_id AS caused_by_deployment,\n        d.deployment_finished_date,\n        DATE_FORMAT(d.deployment_finished_date, '%y/%m') AS deployment_finished_month\n    FROM incidents i\n    JOIN repos r ON r.id = i.scope_id\n    LEFT JOIN project_incident_deployment_relationships pim\n        ON i.id = pim.id\n    JOIN _deployments d\n        ON pim.deployment_id = d.deployment_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND $__timeFilter(i.resolution_date)\n),\n\n_recovery_time_ranks AS (\n    SELECT\n        *,\n        percent_rank() OVER (\n            ORDER BY TIMESTAMPDIFF(MINUTE, deployment_finished_date, incident_resolution_date)\n        ) AS ranks\n    FROM _incidents_for_deployments\n),\n\n_median_recovery_time AS (\n    SELECT\n        MAX(\n            TIMESTAMPDIFF(\n                MINUTE,\n                deployment_finished_date,\n                incident_resolution_date\n            )\n        ) AS median_recovery_time\n    FROM _recovery_time_ranks\n    WHERE ranks <= 0.5\n),\n\n_is_collected_data AS (\n    SELECT\n        CASE\n            WHEN (SELECT COUNT(*) FROM _deployments) = 0\n             AND (SELECT COUNT(*) FROM _incidents_for_deployments) = 0\n                THEN 'No deployments and incidents'\n            WHEN (SELECT COUNT(*) FROM _deployments) = 0\n                THEN 'No Deployments'\n            WHEN (SELECT COUNT(*) FROM _incidents_for_deployments) = 0\n                THEN 'No Incidents'\n            ELSE 'OK'\n        END AS is_collected\n),\n\n_metric_recovery_time_2023_report AS (\n    SELECT\n        CASE\n            WHEN ('$dora_report') <> '2023' THEN NULL\n\n            WHEN is_collected = 'No deployments and incidents'\n                THEN 'N/A. Please check if you have collected deployments and incidents.'\n            WHEN is_collected = 'No Deployments'\n                THEN 'N/A. Please check if you have collected deployments.'\n            WHEN is_collected = 'No Incidents'\n                THEN 'N/A. Please check if you have collected incidents.'\n\n            WHEN median_recovery_time < 60\n                THEN CONCAT(ROUND(median_recovery_time / 60, 1), '(elite)')\n            WHEN median_recovery_time < 24 * 60\n                THEN CONCAT(ROUND(median_recovery_time / 60, 1), '(high)')\n            WHEN median_recovery_time < 7 * 24 * 60\n                THEN CONCAT(ROUND(median_recovery_time / 60, 1), '(medium)')\n            WHEN median_recovery_time >= 7 * 24 * 60\n                THEN CONCAT(ROUND(median_recovery_time / 60, 1), '(low)')\n            ELSE 'No data'\n        END AS median_recovery_time\n    FROM _median_recovery_time, _is_collected_data\n),\n\n-- ****** 2021 Report ******\n-- Metric 4: Median Time To Restore Service (MTTR)\n\n_incidents AS (\n    SELECT\n        DISTINCT i.id,\n        CAST(lead_time_minutes AS SIGNED) AS lead_time_minutes\n    FROM incidents i\n    JOIN repos r ON r.id = i.scope_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND $__timeFilter(i.resolution_date)\n),\n\n_median_mttr_ranks AS (\n    SELECT\n        *,\n        percent_rank() OVER (ORDER BY lead_time_minutes) AS ranks\n    FROM _incidents\n),\n\n_median_mttr AS (\n    SELECT MAX(lead_time_minutes) AS median_time_to_resolve\n    FROM _median_mttr_ranks\n    WHERE ranks <= 0.5\n),\n\n_metric_mttr_2021_report AS (\n    SELECT\n        CASE\n            WHEN ('$dora_report') <> '2021' THEN NULL\n\n            WHEN median_time_to_resolve < 60\n                THEN CONCAT(ROUND(median_time_to_resolve / 60, 1), '(elite)')\n            WHEN median_time_to_resolve < 24 * 60\n                THEN CONCAT(ROUND(median_time_to_resolve / 60, 1), '(high)')\n            WHEN median_time_to_resolve < 7 * 24 * 60\n                THEN CONCAT(ROUND(median_time_to_resolve / 60, 1), '(medium)')\n            WHEN median_time_to_resolve >= 7 * 24 * 60\n                THEN CONCAT(ROUND(median_time_to_resolve / 60, 1), '(low)')\n            ELSE 'N/A. Please check if you have collected incidents.'\n        END AS median_time_to_resolve\n    FROM _median_mttr\n)\n\nSELECT median_recovery_time AS median_time_in_hour\nFROM _metric_recovery_time_2023_report\nWHERE ('$dora_report') = '2023'\n\nUNION\n\nSELECT median_time_to_resolve\nFROM _metric_mttr_2021_report\nWHERE ('$dora_report') = '2021';\n"
    }
   ]
  },
  {
   "title": "Monthly deployments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Metric 1: Number of deployments per month\nWITH _deployments AS (\n    SELECT \n        DATE_FORMAT(deployment_finished_date, '%y/%m') AS month,\n        COUNT(cicd_deployment_id) AS deployment_count\n    FROM (\n        SELECT\n            cdc.cicd_deployment_id,\n            MAX(cdc.finished_date) AS deployment_finished_date\n        FROM cicd_deployment_commits cdc\n        JOIN repos r\n            ON r.id = cdc.repo_id\n        WHERE\n            (\n                '${project:raw}' = '$__all'\n                OR r.name IN (${project:singlequote})\n            )\n            AND cdc.result = 'SUCCESS'\n            AND cdc.environment = 'PRODUCTION'\n        GROUP BY 1\n        HAVING $__timeFilter(MAX(cdc.finished_date))\n    ) AS _production_deployments\n    GROUP BY 1\n)\n\nSELECT \n    cm.month, \n    COALESCE(d.deployment_count, 0) AS `Deployment Count`\nFROM calendar_months cm\nLEFT JOIN _deployments d \n    ON cm.month = d.month\nWHERE cm.month_timestamp BETWEEN\n    DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01'))\n    AND\n    DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'));\n"
    }
   ]
  },
  {
   "title": "Median Lead Time for Changes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Metric 2: median change lead time per month\nWITH _pr_stats AS (\n    SELECT\n        DISTINCT pr.id,\n        DATE_FORMAT(cdc.finished_date, '%y/%m') AS month,\n        ppm.pr_cycle_time\n    FROM pull_requests pr\n    JOIN project_pr_metrics ppm \n        ON ppm.id = pr.id\n    JOIN cicd_deployment_commits cdc \n        ON ppm.deployment_commit_id = cdc.id\n    JOIN repos r\n        ON r.id = pr.base_repo_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND pr.merged_date IS NOT NULL\n        AND ppm.pr_cycle_time IS NOT NULL\n        AND $__timeFilter(cdc.finished_date)\n),\n\n_find_median_clt_each_month_ranks AS (\n    SELECT \n        *,\n        percent_rank() OVER (\n            PARTITION BY month \n            ORDER BY pr_cycle_time\n        ) AS ranks\n    FROM _pr_stats\n),\n\n_clt AS (\n    SELECT \n        month,\n        MAX(pr_cycle_time) AS median_change_lead_time\n    FROM _find_median_clt_each_month_ranks\n    WHERE ranks <= 0.5\n    GROUP BY month\n)\n\nSELECT \n    cm.month,\n    CASE \n        WHEN _clt.median_change_lead_time IS NULL THEN 0 \n        ELSE _clt.median_change_lead_time / 60 \n    END AS `Median Change Lead Time In Hours`\nFROM calendar_months cm\nLEFT JOIN _clt \n    ON cm.month = _clt.month\nWHERE cm.month_timestamp BETWEEN\n    DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) \n    AND \n    DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'));\n"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate per month\nWITH _deployments AS (\n    SELECT\n        cdc.cicd_deployment_id AS deployment_id,\n        MAX(cdc.finished_date) AS deployment_finished_date\n    FROM cicd_deployment_commits cdc\n    JOIN project_mapping pm\n        ON cdc.cicd_scope_id = pm.row_id\n       AND pm.`table` = 'cicd_scopes'\n    JOIN repos r\n        ON r.id = pm.row_id\n    WHERE\n        (\n            '${project:raw}' = '$__all'\n            OR r.name IN (${project:singlequote})\n        )\n        AND cdc.result = 'SUCCESS'\n        AND cdc.environment = 'PRODUCTION'\n    GROUP BY 1\n    HAVING $__timeFilter(MAX(cdc.finished_date))\n),\n\n_failure_caused_by_deployments AS (\n    SELECT\n        d.deployment_id,\n        d.deployment_finished_date,\n        COUNT(\n            DISTINCT CASE\n                WHEN i.id IS NOT NULL THEN d.deployment_id\n                ELSE NULL\n            END\n        ) AS has_incident\n    FROM _deployments d\n    LEFT JOIN project_incident_deployment_relationships pim\n        ON d.deployment_id = pim.deployment_id\n    LEFT JOIN incidents i\n        ON pim.id = i.id\n    GROUP BY 1,2\n),\n\n_change_failure_rate_for_each_month AS (\n    SELECT\n        DATE_FORMAT(deployment_finished_date, '%y/%m') AS month,\n        CASE\n            WHEN COUNT(deployment_id) = 0 THEN NULL\n            ELSE SUM(has_incident) / COUNT(deployment_id)\n        END AS change_failure_rate\n    FROM _failure_caused_by_deployments\n    GROUP BY 1\n)\n\nSELECT\n    cm.month,\n    cfr.change_failure_rate AS `Change Failure Rate`\nFROM calendar_months cm\nLEFT JOIN _change_failure_rate_for_each_month cfr\n    ON cm.month = cfr.month\nWHERE cm.month_timestamp BETWEEN\n    DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01'))\n    AND\n    DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'));\n"
    }
   ]
  },
  {
   "title": "${title_value}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\nWITH _deployments AS (\n  SELECT\n    cdc.cicd_deployment_id AS deployment_id,\n    MAX(cdc.finished_date) AS deployment_finished_date\n  FROM cicd_deployment_commits cdc\n  JOIN project_mapping pm\n      ON cdc.cicd_scope_id = pm.row_id\n     AND pm.`table` = 'cicd_scopes'\n  JOIN repos r\n      ON r.id = pm.row_id\n  WHERE\n      (\n          '${project:raw}' = '$__all'\n          OR r.name IN (${project:singlequote})\n      )\n      AND cdc.result = 'SUCCESS'\n      AND cdc.environment = 'PRODUCTION'\n  GROUP BY 1\n  HAVING $__timeFilter(MAX(cdc.finished_date))\n),\n\n_incidents_for_deployments AS (\n  SELECT\n    i.id AS incident_id,\n    i.created_date AS incident_create_date,\n    i.resolution_date AS incident_resolution_date,\n    fd.deployment_id AS caused_by_deployment,\n    fd.deployment_finished_date,\n    DATE_FORMAT(fd.deployment_finished_date, '%y/%m') AS deployment_finished_month\n  FROM incidents i\n  LEFT JOIN project_incident_deployment_relationships pim ON i.id = pim.id\n  JOIN _deployments fd ON pim.deployment_id = fd.deployment_id\n  WHERE $__timeFilter(i.resolution_date)\n),\n\n_recovery_time_ranks AS (\n  SELECT\n    *,\n    percent_rank() OVER (\n        PARTITION BY deployment_finished_month\n        ORDER BY TIMESTAMPDIFF(\n            MINUTE,\n            deployment_finished_date,\n            incident_resolution_date\n        )\n    ) AS ranks\n  FROM _incidents_for_deployments\n),\n\n_median_recovery_time AS (\n  SELECT\n    deployment_finished_month,\n    MAX(\n      TIMESTAMPDIFF(\n        MINUTE,\n        deployment_finished_date,\n        incident_resolution_date\n      )\n    ) AS median_recovery_time\n  FROM _recovery_time_ranks\n  WHERE ranks <= 0.5\n  GROUP BY deployment_finished_month\n),\n\n_metric_recovery_time_2023_report AS (\n  SELECT\n    cm.month,\n    CASE\n      WHEN m.median_recovery_time IS NULL THEN 0\n      ELSE m.median_recovery_time / 60\n    END AS median_recovery_time_in_hour\n  FROM calendar_months cm\n  LEFT JOIN _median_recovery_time m\n      ON cm.month = m.deployment_finished_month\n  WHERE month_timestamp BETWEEN\n        DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01'))\n    AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))\n),\n\n--  ***** 2021 report ***** --\n-- Metric 4: MTTR\n_incidents AS (\n  SELECT\n    DISTINCT i.id,\n    DATE_FORMAT(i.resolution_date, '%y/%m') AS month,\n    CAST(lead_time_minutes AS SIGNED) AS lead_time_minutes\n  FROM incidents i\n  JOIN project_mapping pm\n      ON i.scope_id = pm.row_id\n     AND pm.`table` = i.`table`\n  JOIN repos r\n      ON r.id = pm.row_id\n  WHERE\n      (\n          '${project:raw}' = '$__all'\n          OR r.name IN (${project:singlequote})\n      )\n      AND i.lead_time_minutes IS NOT NULL\n),\n\n_find_median_mttr_each_month_ranks AS (\n  SELECT *,\n    percent_rank() OVER (\n        PARTITION BY month\n        ORDER BY lead_time_minutes\n    ) AS ranks\n  FROM _incidents\n),\n\n_mttr AS (\n  SELECT\n    month,\n    MAX(lead_time_minutes) AS median_time_to_resolve\n  FROM _find_median_mttr_each_month_ranks\n  WHERE ranks <= 0.5\n  GROUP BY month\n),\n\n_metric_mttr_2021_report AS (\n  SELECT\n    cm.month,\n    CASE\n      WHEN m.median_time_to_resolve IS NULL THEN 0\n      ELSE m.median_time_to_resolve / 60\n    END AS median_time_to_resolve_in_hour\n  FROM calendar_months cm\n  LEFT JOIN _mttr m ON cm.month = m.month\n  WHERE month_timestamp BETWEEN\n        DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01'))\n    AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))\n)\n\nSELECT\n  cm.month,\n  CASE\n    WHEN '${dora_report}' = '2023' THEN mrt.median_recovery_time_in_hour\n    WHEN '${dora_report}' = '2021' THEN mm.median_time_to_resolve_in_hour\n  END AS '${title_value} In Hours'\nFROM calendar_months cm\nLEFT JOIN _metric_recovery_time_2023_report mrt ON cm.month = mrt.month\nLEFT JOIN _metric_mttr_2021_report mm ON cm.month = mm.month\nWHERE month_timestamp BETWEEN\n      DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01'))\n  AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'));\n"
    }
   ]
  }
 ]
}